#!/usr/bin/env bash

set -e

# Compare 2 files generated by e2e_collect. This ensures elements are sorted by version

type -f jq > /dev/null || {
  echo Please install jq
  exit 1
}

test "$#" -ne 2 && echo "Usage: ./e2e_compare.sh FILE1 FILE2" && exit 1

# jq would output the whole graph with elements in "nodes" sorted by "version"
# to ensure the json output is identical for the equal graphs
diff <(jq -S '.nodes |= sort_by(.version)' ${1}) <(jq -S '.nodes |= sort_by(.version)' ${2})
