[source.crates-io]
replace-with = "vendored-sources"

[source."https://github.com/camallo/dkregistry-rs.git"]
git = "https://github.com/camallo/dkregistry-rs.git"
rev = "0b1dbf63b2b74919d210819a490c18de3bd4e947"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
