
[source.crates-io]
replace-with = "vendored-sources"

[source."https://github.com/camallo/dkregistry-rs.git"]
git = "https://github.com/camallo/dkregistry-rs.git"
rev = "abb58c140fba8bebae3d20ea4290c52147468e27"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
