[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/camallo/dkregistry-rs.git?rev=89d190c313653afabee66032a4c88efd804f0829"]
git = "https://github.com/camallo/dkregistry-rs.git"
rev = "89d190c313653afabee66032a4c88efd804f0829"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
